const fs = require('fs');
const path = require('path');

const newEnKeys = {
    "markAllAsRead": "Mark all as read",
    "youAreCaughtUp": "You're all caught up",
    "dashboardPristine": "Your curatorial dashboard is pristine. Check back later for new heritage updates.",
    "markRead": "Mark Read",
    "viewAll": "View All",
    "showLess": "Show Less",
    "emptyMasterclasses": "No masterclasses found matching your search.",
    "loadingMasterclasses": "Loading masterclasses...",
    "courseNotFound": "Course not found",
    "backToCourses": "Back to Masterclasses",
    "completed": "Completed",
    "unknown": "Unknown",
    "masterArtisanHindi": "मास्टर शिल्पकार",
    "lessons": "Lessons",
    "duration": "Duration",
    "learners": "Learners",
    "enrolled": "Enrolled",
    "enrollNow": "Enroll Now",
    "viewEnrolled": "View Enrolled",
    "editCourse": "Edit Course",
    "deleteCourse": "Delete Course",
    "curriculum": "Curriculum",
    "enrollToWatch": "Enroll in this course to unlock all videos and start learning.",
    "modulesUploading": "Modules are currently being uploaded. Check back soon.",
    "playVideo": "Play Video",
    "enrollSuccess": "You've been enrolled! Start learning.",
    "noLearners": "No learners enrolled yet.",
    "deleteConfirmTitle": "Delete Course?",
    "deleteConfirmDesc": "Are you sure you want to delete",
    "startOffer": "Start an Offer",
    "whatIsOfferRegarding": "What is this offer regarding?",
    "whatIsConversationRegarding": "What is this conversation regarding?",
    "skipJustChat": "Skip, just chat",
    "aboutProduct": "About a Product?",
    "searchByName": "Search by Name",
    "searchByIndustry": "Search by Industry",
    "artisanName": "Artisan Name",
    "industry": "Industry",
    "selectIndustry": "— Select an industry —",
    "selectArtisan": "— Select an artisan —",
    "seeProducts": "See Products",
    "personalInfo": "Personal Information",
    "fullName": "Full Name",
    "location": "Location",
    "bioDescription": "Bio / Description",
    "securityPassword": "Security & Password",
    "currentPassword": "Current Password",
    "currentPasswordHindi": "पुरानी गोपनीयता",
    "newPassword": "New Password",
    "confirmNewPassword": "Confirm New Password",
    "notice": "Notice",
    "close": "Close",
    "artisanNotFound": "Artisan not found.",
    "goBack": "Go Back",
    "the": "The",
    "archive": "Archive",
    "newConversation": "New Conversation",
    "learning": "Learning"
};

const newHiKeys = {
    "markAllAsRead": "सभी को पढ़ा हुआ चिह्नित करें",
    "youAreCaughtUp": "आप सभी अपडेट से अवगत हैं",
    "dashboardPristine": "आपका डैशबोर्ड अद्यतित है। नए विरासत अपडेट के लिए बाद में देखें।",
    "markRead": "पढ़ा हुआ चिह्नित करें",
    "viewAll": "सभी देखें",
    "showLess": "कम दिखाएं",
    "emptyMasterclasses": "आपकी खोज से मेल खाने वाला कोई मास्टरक्लास नहीं मिला।",
    "loadingMasterclasses": "मास्टरक्लास लोड हो रहे हैं...",
    "courseNotFound": "पाठ्यक्रम नहीं मिला",
    "backToCourses": "मास्टरक्लास पर वापस जाएं",
    "completed": "पूरा हुआ",
    "unknown": "अज्ञात",
    "masterArtisanHindi": "मास्टर शिल्पकार",
    "lessons": "पाठ",
    "duration": "अवधि",
    "learners": "शिक्षार्थी",
    "enrolled": "नामांकित",
    "enrollNow": "अभी नामांकन करें",
    "viewEnrolled": "नामांकित देखें",
    "editCourse": "पाठ्यक्रम संपादित करें",
    "deleteCourse": "पाठ्यक्रम हटाएं",
    "curriculum": "पाठ्यक्रम-सूची",
    "enrollToWatch": "सभी वीडियो अनलॉक करने और सीखना शुरू करने के लिए पाठ्यक्रम में नामांकन करें।",
    "modulesUploading": "मॉड्यूल वर्तमान में अपलोड किए जा रहे हैं। जल्द ही वापस देखें।",
    "playVideo": "वीडियो चलाएं",
    "enrollSuccess": "आपका नामांकन हो गया है! सीखना शुरू करें।",
    "noLearners": "अभी तक कोई शिक्षार्थी नामांकित नहीं है।",
    "deleteConfirmTitle": "पाठ्यक्रम हटाएं?",
    "deleteConfirmDesc": "क्या आप वाकई हटाना चाहते हैं",
    "startOffer": "एक प्रस्ताव शुरू करें",
    "whatIsOfferRegarding": "यह प्रस्ताव किस बारे में है?",
    "whatIsConversationRegarding": "यह बातचीत किस बारे में है?",
    "skipJustChat": "छोड़ें, बस चैट करें",
    "aboutProduct": "किसी उत्पाद के बारे में?",
    "searchByName": "नाम से खोजें",
    "searchByIndustry": "उद्योग से खोजें",
    "artisanName": "शिल्पकार का नाम",
    "industry": "उद्योग",
    "selectIndustry": "— एक उद्योग चुनें —",
    "selectArtisan": "— एक शिल्पकार चुनें —",
    "seeProducts": "उत्पाद देखें",
    "personalInfo": "व्यक्तिगत जानकारी",
    "fullName": "पूरा नाम",
    "location": "स्थान",
    "bioDescription": "विवरण / जीवनी",
    "securityPassword": "सुरक्षा और पासवर्ड",
    "currentPassword": "वर्तमान पासवर्ड",
    "currentPasswordHindi": "पुरानी गोपनीयता",
    "newPassword": "नया पासवर्ड",
    "confirmNewPassword": "नये पासवर्ड की पुष्टि करें",
    "notice": "सूचना",
    "close": "बंद करें",
    "artisanNotFound": "शिल्पकार नहीं मिला।",
    "goBack": "वापस जाएं",
    "the": "द",
    "archive": "संग्रह",
    "newConversation": "नयी बातचीत",
    "learning": "सीखना"
};

const enPath = path.resolve('./CraftConnect/src/locales/en.json');
const hiPath = path.resolve('./CraftConnect/src/locales/hi.json');

function updateLocales(p, newObj) {
    let raw = fs.readFileSync(p, 'utf-8');
    let obj = JSON.parse(raw); 
    
    Object.assign(obj.extended, newObj);
    
    fs.writeFileSync(p, JSON.stringify(obj, null, 2));
}

updateLocales(enPath, newEnKeys);
updateLocales(hiPath, newHiKeys);
