export const INDUSTRY_OPTIONS = [
  "Bamboo Craft",
  "Bell Metal / Dhokra",
  "Cowrie & Shell Craft",
  "Godna / Tattoo Art",
  "Gourd (Tuma) Craft",
  "Handloom & Weaving",
  "Jewellery & Ornaments",
  "Kosa Silk",
  "Leather Craft",
  "Painting & Folk Art",
  "Pottery & Terracotta",
  "Stone Carving",
  "Textile Printing",
  "Tiles & Mosaic",
  "Wood Carving",
  "Wrought Iron / Loha Shilp",
  "Other",
] as const;
